version: 2
jobs:
  build:
    docker:
      - image: cimg/node:8.17
    working_directory: ~/react-minesweeper
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # - run: npm test
      - run: npm run build
      - run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
